### ISSUE TITLE
Error: "Failed to add plugin: Failed to import plugin: "schema.extra" is not allowed"

### ISSUE THREAD

**Issue by acseven** [melohagan/budibase-datasource-supabase#1]
Hi,
I'm getting this error when trying to install the plugin, by uploading the file or entering the github URL:

``
 Failed to add plugin: Failed to import plugin: "schema.extra" is not allowed
``

<img width="1070" alt="s" src="https://user-images.githubusercontent.com/1176371/191864870-64ca3713-a0ac-4b70-8c7f-20f3e37b028d.png">

Is this how it should be done?

**Comment by melohagan** [comment]
Hi @acseven 

This bug has been fixed, and will be released at the end of next week - 27th September. 
https://github.com/Budibase/budibase/pull/7857

In the meantime if you just want to test it out, you can run the `develop` branch locally.
