### ISSUE TITLE
Table name not showing up while trying to update row

### ISSUE THREAD

**Issue by AshishKapoor** [melohagan/budibase-datasource-supabase#3]
# Budibase
<img width="1276" alt="Screenshot 2023-07-29 at 12 04 50 PM" src="https://github.com/melohagan/budibase-datasource-supabase/assets/5203107/f23bf3d0-b115-4476-85b8-b83c667eaba1">

# Supabase
<img width="1278" alt="Screenshot 2023-07-29 at 12 06 04 PM" src="https://github.com/melohagan/budibase-datasource-supabase/assets/5203107/3109b3e3-7a48-43b5-a86a-7dc251ba5065">

# Query
<img width="586" alt="Screenshot 2023-07-29 at 12 07 33 PM" src="https://github.com/melohagan/budibase-datasource-supabase/assets/5203107/c7af866d-f82a-499d-b3ec-5b6dc9f9446c">

**Comment by melohagan** [comment]
Hi @AshishKapoor 

There's a couple of things here. When using a [custom query](https://docs.budibase.com/docs/data-sources#custom-queries) you cannot use the **Save Row** action, instead you must use the **Execute Query** action.

Furthermore, if you want to save a row, your query will have to have a *Function* of Create or Update - your current query is 'Read'. 

[This tutorial](https://docs.budibase.com/docs/data-sources#tutorial-posting-form-data-to-a-custom-query) shows you how to save form data through a custom query.
