### ISSUE TITLE
Bucket  Uploads?

### ISSUE THREAD

**Issue by gelinger777** [melohagan/budibase-datasource-supabase#4]
Hi, a quick question... 
How do you do uploads in Budibase? I am exploring it as an option for admin panel, but can't quite understand how to implement the image uploads/management....

**Comment by melohagan** [comment]
https://docs.budibase.com/docs/attachments

**Comment by gelinger777** [comment]
You do upload into separate MinIO instance and don't use the built in buckets of Supabase. Thats the problem.
