### ISSUE TITLE
Query Error: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by peter-ergisi** [melohagan/budibase-datasource-supabase#5]
Hello,

I am encountering the following error when executing a query:

"Query Error: Cannot convert undefined or null to object"

Here is the given JSON result:

`{
  "error": {
    "message": "FetchError: fetch failed",
    "details": "",
    "hint": "",
    "code": ""
  },
  "data": null,
  "body": null,
  "count": null,
  "status": 400,
  "statusText": "Bad Request"
}`

The Supabase logs indicate that the request was made and received a 200 response.

Could you please advise on this matter? Is it necessary to update the project?

Thank you.

**Comment by peter-ergisi** [comment]
Here is the given JSON result

{
  "error": {
    "message": "FetchError: fetch failed",
    "details": "",
    "hint": "",
    "code": ""
  },
  "data": null,
  "body": null,
  "count": null,
  "status": 400,
  "statusText": "Bad Request"
}

**Comment by melohagan** [comment]
Hey @peter-ergisi 

You wouldn't mind providing screenshots of your query so I can see how you've set it up please?

**Comment by peter-ergisi** [comment]
> Hey @peter-ergisi
> 
> You wouldn't mind providing screenshots of your query so I can see how you've set it up please?

Hey, thank you so much for getting back to me.

Here is the query
![image](https://github.com/melohagan/budibase-datasource-supabase/assets/43963547/b327877b-7cb6-4d39-9115-90104319ac27)

Here is the configuration
![image](https://github.com/melohagan/budibase-datasource-supabase/assets/43963547/64ba7960-d94f-4f72-a258-9f833b477be8)


Here is the database
![image](https://github.com/melohagan/budibase-datasource-supabase/assets/43963547/5e28a045-6e23-48ad-9307-a1cce71225d7)
(test values)

I might have been confused by the error messages while testing. I have since got the message "Query executed successfully" reliably but with the same JSON response.

Could it be a conflict with Traefik?

**Comment by peter-ergisi** [comment]
Have solved somehow :)
